---
version: "3.1"
services:

## 00 ##
## Torrent Downloader ##
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=Asia/Kuwait
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /home/morris/docker/arr/config/qbittorrent-config:/config
      - /media/data/torrents:/data/torrents
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped

## download nzb's ##
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=Asia/Kuwait
    volumes:
      - /home/morris/docker/arr/config/sabnzbd-config:/config
      - /media/data/usenet:/data/usenet
    ports:
      - "8081:8080"
    restart: unless-stopped

## 10 ##
## Track Indexers ##
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    depends_on: 
      - qbittorrent
    environment:
      - PUID=13010
      - PGID=13000
      - UMASK=002
      - TZ=Asia/Kuwait
    volumes:
      - /home/morris/docker/arr/config/prowlarr-config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

## Track Indexers ##
#  jackett:
#    image: lscr.io/linuxserver/jackett:latest
#    container_name: jackett
#    environment:
#      - PUID=13011
#      - PGID=13000
#      - UMASK=002
#      - TZ=Asia/Kuwait
#    volumes:
#      - /home/morris/docker/arr/config/prowlarr-config:/config
#    ports:
#      - "9117:9117"
#    restart: unless-stopped

## 20 ##
##Manage Movies##
  radarr1:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    depends_on:
      - qbittorrent
      - prowlarr
    environment:
      - PUID=13020
      - PGID=13000
      - UMASK=002
      - TZ=Asia/Kuwait
    volumes:
      - /home/morris/docker/arr/config/radarr-config:/config
      - /media/data:/data
    ports:
      - "7878:7878"
    restart: unless-stopped

##Manage Anime Movies##  
  radarr2:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr_anime
    depends_on:
      - qbittorrent
      - prowlarr
    environment:
      - PUID=13021
      - PGID=13000
      - UMASK=002
      - TZ=Asia/Kuwait
    volumes:
      - /home/morris/docker/arr/config/radarr_anime-config:/config
      - /media/data:/data
    ports:
      - "7877:7878"
    restart: unless-stopped

## Manage TV Shows ##
  sonarr1:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr_tv
    depends_on:
      - qbittorrent
      - prowlarr
    environment:
      - PUID=13024
      - PGID=13000
      - UMASK=002
      - TZ=Asia/Kuwait
    volumes:
      - /home/morris/docker/arr/config/sonarr-config:/config
      - /media/data:/data
    ports:
      - "8989:8989"
    restart: unless-stopped

## Manage Anime Shows ##
  sonarr2:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr_anime
    depends_on:
      - qbittorrent
      - prowlarr
    environment:
      - PUID=13025
      - PGID=13000
      - UMASK=002
      - TZ=Asia/Kuwait
    volumes:
      - /home/morris/docker/arr/config/sonarr_anime-config:/config
      - /media/data:/data
    ports:
      - "8988:8989"
    restart: unless-stopped

## Download Subtitles ##
#  bazarr:
#    image: lscr.io/linuxserver/bazarr:latest
#    container_name: bazarr
#    depends_on:
#      - sonarr
#      - radarr
#    environment:
#      - PUID=13028
#      - PGID=13000
#      - TZ=Asia/Kuwait
#      - WEBUI_PORTS=6767/tcp,6767/udp
#    volumes:
#      - /home/morris/docker/arr/config/bazarr-config:/config
#      - /home/morris/docker/arr/data/media:/media
#    ports:
#      - "6767:6767"
#    restart: unless-stopped

##30 ##
## Media Server ##
#  plex:
#    image: lscr.io/linuxserver/plex:latest
#    container_name: plex
#    network_mode: host
#    environment:
#      - PUID=13030
#      - PGID=13000
#      - VERSION=docker
#      - PLEX_CLAIM=claim-xrAos_DwpH4_9zfhPZwp
#      - TZ=Asia/Kuwait
#    ports:
#      - " : "
#    volumes:
#      - /home/morris/docker/arr/config/plex-config:/config
#      - /home/morris/docker/arr/data/media:/media
#    restart: unless-stopped

## Show and Movie Request Manager for Plex ##
#  overseerr:
#    image: lscr.io/linuxserver/overseerr:latest
#    container_name: overseerr
#    depends_on:
#      - plex
#    environment:
#      - PUID=13031
#      - PGID=13000
#      - UMASK=002
#      - TZ=Asia/Kuwait
#    volumes:
#      - /home/morris/docker/arr/config/overseerr-config:/config
#    ports:
#      - "5056:5055"
#    restart: unless-stopped

## Monitoring Aplication for Plex ##
#  tautulli:
#    image: lscr.io/linuxserver/tautulli:latest
#    container_name: tautulli
#    depends_on:
#      - plex
#    environment:
#      - PUID=13032
#      - PGID=13000
#      - TZ=Asia/Kuwait
#    volumes:
#      - /home/morris/docker/arr/config/tautulli-config:/config
#    ports:
#      - "8181:8181"
#    restart: unless-stopped

## 40 ##
## Media Server ##
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=13040
      - PGID=13000
      - UMASK=002
      - TZ=Asia/Kuwait
    volumes:
      - /home/morris/docker/arr/config/jellyfin-config:/config
      - /media/data/media:/media
    ports:
      - "8096:8096"
    restart: unless-stopped

## Show and Movie Request Manager for Jellyfin ##
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    depends_on:
      - jellyfin
    environment:
      - PUID=13041
      - PGID=13000
      - UMASK=002
      - TZ=Asia/Kuwait
    volumes:
      - /home/morris/docker/arr/config/jellyseerr-config:/app/config
    ports:
      - "5055:5055"
    restart: unless-stopped

##60 ##
## Manage Music ##
#  lidarr:
#    image: lscr.io/linuxserver/lidarr:latest
#    container_name: lidarr
#    environment:
#      - PUID=13060
#      - PGID=13000
#      - UMASK=002
#      - TZ=Asia/Kuwait
#    volumes:
#      - /home/morris/docker/arr/config/lidarr-config:/config
#      - /home/morris/docker/arr/data:/data
#    ports:
#      - "8686:8686"
#    restart: unless-stopped

##70 ##
## Ebook Server ##  
#  calibre:
#    image: lscr.io/linuxserver/calibre:latest
#    container_name: calibre
#    environment:
#      - PUID=13070
#      - PGID=13000
#      - UMASK=002
#      - TZ=Asia/Kuwait
#    volumes:
#      - /home/morris/docker/arr/config/calibre-config:/config
#      - /media/data:/data
#    ports:
#      - 8082:8080
#      - 8181:8181
#      - 8081:8081
#    restart: unless-stopped

## Manage Books ##
#  readarr:
#    image: lscr.io/linuxserver/readarr:develop
#    container_name: readarr
#    depends_on:
#      - qbittorrent
#      - prowlarr
#    environment:
#      - PUID=13071
#      - PGID=13000
#      - UMASK=002
#      - TZ=Asia/Kuwait
#    volumes:
#      - /home/morris/docker/arr/config/readarr-config:/config
#      - /media/data:/data
#    ports:
#      - "8787:8787"
#    restart: unless-stopped

## Mange Comic Books ##
#  mylar3:
#    image: lscr.io/linuxserver/mylar3:latest
#    container_name: mylar3
#    environment:
#      - PUID=13072
#      - PGID=13000
#      - UMASK=002
#      - TZ=Asia/Kuwait
#    volumes:
#      - /home/morris/docker/arr/config/mylar-config:/config
#      - /home/morris/docker/arr/data:/data
#    ports:
#      - "8090:8090"
#    restart: unless-stopped

## 80 ##
## Dashboards ##
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=13080
      - PGID=13000
      - TZ=Asia/Kuwait
    volumes:
      - /home/morris/docker/arr/config/heimdall-config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
